services:
  dynamodb-local:
    image: amazon/dynamodb-local:2.0.0
    command: -jar DynamoDBLocal.jar -inMemory
    ports:
      - 8000:8000
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    tty: true
    container_name: dynamodb-admin
    ports:
      - '8001:8001'
    depends_on:
      - dynamodb-local
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
